from typing import TypedDict, Optional, List, Dict, Any
from ollama import Client
import chromadb
import chromadb.utils.embedding_functions as embedding_functions
import os
import re
import base64
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

DB_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "chroma_db")

# Environment configurations
OLLAMA_BASE_URL = os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434")
OLLAMA_MODEL = os.environ.get("OLLAMA_MODEL", "llama3.1")
OLLAMA_VISION_MODEL = os.environ.get("OLLAMA_VISION_MODEL", "llama3.2-vision")

# Initialize Ollama client pointing to the specific host
ollama_client = Client(host=OLLAMA_BASE_URL)

# Setup Chroma Client
client = chromadb.PersistentClient(path=DB_DIR)
default_ef = embedding_functions.DefaultEmbeddingFunction()
try:
    collection = client.get_collection(
        name="agri_compliance", embedding_function=default_ef
    )
except Exception:
    collection = None


def clean_think_tags(text: str) -> str:
    """Removes <think>...</think> tags and their contents often generated by thinking models."""
    cleaned = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL)
    return cleaned.strip()


def translate_to_english_helper(query: str, lang: str) -> str:
    """Translates the native user query to English."""
    if lang == "en" or lang.lower() == "english" or lang.startswith("en"):
        return query

    prompt = f"Translate the following text from {lang} to English. Preserve any local agricultural terms by transliterating them. Return ONLY the English translation.\nText: {query}"
    try:
        response = ollama_client.chat(
            model=OLLAMA_MODEL, messages=[{"role": "user", "content": prompt}]
        )
        return (
            clean_think_tags(response.get("message", {}).get("content", "")).strip()
            or query
        )
    except Exception:
        return query


def check_intent_helper(query: str) -> bool:
    """Checks if the query is agricultural."""
    prompt = f"Classify this query: '{query}'. Is this query related to agriculture, farming, crops, weather, or pests? Reply with ONLY 'YES' or 'NO'."
    try:
        response = ollama_client.chat(
            model=OLLAMA_MODEL, messages=[{"role": "user", "content": prompt}]
        )
        ans = (
            clean_think_tags(response.get("message", {}).get("content", ""))
            .strip()
            .upper()
        )
        return "YES" in ans
    except Exception:
        return True  # Default to true if fails


def fetch_rag_context_helper(query: str) -> List[str]:
    """Fetches relevant compliance guidelines from Vector DB."""
    if not collection:
        return []
    try:
        results = collection.query(query_texts=[query], n_results=3)
        return results["documents"][0] if results["documents"] else []
    except Exception:
        return []


def build_draft_prompt(
    docs: List[str],
    eng_query: str,
    target_lang: str,
    weather: str = "",
    symptoms: str = "",
) -> str:
    context = "\n\n".join(docs)
    return f"""You are a strict agricultural advisor in India. 
Context from official guidelines:
{context}

User Query (English): {eng_query}
Image Symptoms: {symptoms}
Weather Context: {weather}

1. Analyze the context and the user query.
2. Answer the query based ONLY on the context provided above. 
3. If the context does not contain the answer, or if the user asks for a banned chemical, you MUST output EXACTLY: "I do not have enough verified information to answer this safely. Please consult your local Krishi Vigyan Kendra (KVK) official or agricultural officer."
4. DO NOT guess or hallucinate.
5. Translate your final response into {target_lang}. Use simple, conversational language suitable for a farmer. Output your final response in {target_lang}.
"""


def get_vision_response(
    image_bytes: bytes, prompt: str, model=OLLAMA_VISION_MODEL
) -> str:
    """Helper to query Ollama Vision models."""
    try:
        b64_image = base64.b64encode(image_bytes).decode("utf-8")
        response = ollama_client.chat(
            model=model,
            messages=[{"role": "user", "content": prompt, "images": [b64_image]}],
        )
        content = response.get("message", {}).get("content", "")
        return clean_think_tags(content)
    except Exception as e:
        print(f"Ollama Vision Error [{model}]: {e}")
        return f"[Error: Unable to analyze image using '{model}'.]"
