from typing import Optional, List, Dict, Any
from ollama import Client
import chromadb
import chromadb.utils.embedding_functions as embedding_functions
import os
import re
import base64
import time
import json
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

DB_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "chroma_db")

# Environment configurations
OLLAMA_BASE_URL = os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434")
OLLAMA_MODEL = os.environ.get("OLLAMA_MODEL", "llama3.1")
OLLAMA_VISION_MODEL = os.environ.get("OLLAMA_VISION_MODEL", "llama3.2-vision")
DEBUG_MODE = os.environ.get("DEBUG_MODE", "false").lower() == "true"

# Initialize Ollama client pointing to the specific host
ollama_client = Client(host=OLLAMA_BASE_URL)

# Setup Chroma Client
client = chromadb.PersistentClient(path=DB_DIR)
default_ef = embedding_functions.DefaultEmbeddingFunction()
try:
    collection = client.get_collection(
        name="agri_compliance", embedding_function=default_ef
    )
except Exception:
    collection = None


def debug_log(step: str, data: Dict[str, Any]) -> None:
    """Structured debug logging controlled by DEBUG_MODE env var."""
    if not DEBUG_MODE:
        return
    timestamp = time.strftime("%H:%M:%S")
    print(f"\n{'='*60}")
    print(f"[DEBUG {timestamp}] STEP: {step}")
    print(f"{'-'*60}")
    for key, value in data.items():
        val_str = str(value)
        if len(val_str) > 500:
            val_str = val_str[:500] + "... (truncated)"
        print(f"  {key}: {val_str}")
    print(f"{'='*60}\n")


def clean_think_tags(text: str) -> str:
    """Removes <think>...</think> tags and their contents often generated by thinking models."""
    cleaned = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL)
    return cleaned.strip()


def translate_to_english_helper(query: str, lang: str) -> Dict[str, Any]:
    """Translates the native user query to English. Returns dict with translation + metadata."""
    result = {
        "translated_query": query,
        "source_language": lang,
        "was_translated": False,
        "duration_ms": 0,
    }

    if lang == "en" or lang.lower() == "english" or lang.startswith("en"):
        debug_log("TRANSLATE", {"action": "skipped (already English)", "query": query})
        return result

    start = time.time()
    prompt = f"Translate the following text from {lang} to English. Preserve any local agricultural terms by transliterating them. Return ONLY the English translation.\nText: {query}"
    try:
        response = ollama_client.chat(
            model=OLLAMA_MODEL, messages=[{"role": "user", "content": prompt}]
        )
        translated = (
            clean_think_tags(response.get("message", {}).get("content", "")).strip()
            or query
        )
        duration_ms = int((time.time() - start) * 1000)
        result.update({
            "translated_query": translated,
            "was_translated": True,
            "duration_ms": duration_ms,
        })
        debug_log("TRANSLATE", {
            "source_language": lang,
            "original_query": query,
            "translated_query": translated,
            "duration_ms": duration_ms,
            "model": OLLAMA_MODEL,
        })
    except Exception as e:
        debug_log("TRANSLATE", {"error": str(e), "fallback": "using original query"})
    return result


def check_intent_helper(query: str) -> Dict[str, Any]:
    """Checks if the query is agricultural. Returns dict with classification + metadata."""
    start = time.time()
    prompt = f"Is the following query related to agriculture, farming, crops, plant diseases, weather, or pests? Query: '{query}'. Reply with ONLY 'YES' or 'NO'."
    result = {
        "is_agricultural": True,
        "raw_response": "",
        "duration_ms": 0,
    }
    try:
        response = ollama_client.chat(
            model=OLLAMA_MODEL, messages=[{"role": "user", "content": prompt}]
        )
        raw_ans = response.get("message", {}).get("content", "")
        ans = clean_think_tags(raw_ans).strip().upper()
        duration_ms = int((time.time() - start) * 1000)

        # Be permissive: only reject if it explicitly says NO and doesn't say YES
        is_agri = not ("NO" in ans and "YES" not in ans)

        result.update({
            "is_agricultural": is_agri,
            "raw_response": ans,
            "duration_ms": duration_ms,
        })
        debug_log("INTENT", {
            "query": query,
            "raw_model_response": raw_ans.strip(),
            "cleaned_response": ans,
            "is_agricultural": is_agri,
            "duration_ms": duration_ms,
            "model": OLLAMA_MODEL,
        })
    except Exception as e:
        debug_log("INTENT", {"error": str(e), "fallback": "defaulting to agricultural=True"})
    return result


def fetch_rag_context_helper(query: str) -> Dict[str, Any]:
    """Fetches relevant compliance guidelines from Vector DB. Returns docs + similarity scores."""
    start = time.time()
    result: Dict[str, Any] = {
        "documents": [],
        "scores": [],
        "sources": [],
        "duration_ms": 0,
    }

    if not collection:
        debug_log("RAG", {"error": "ChromaDB collection not found", "query": query})
        return result

    try:
        results = collection.query(
            query_texts=[query],
            n_results=3,
            include=["documents", "distances", "metadatas"],
        )
        documents = results["documents"][0] if results["documents"] else []
        distances = results["distances"][0] if results.get("distances") else []
        metadatas = results["metadatas"][0] if results.get("metadatas") else []

        # ChromaDB returns L2 distances; convert to similarity score (lower distance = higher similarity)
        # Similarity = 1 / (1 + distance)
        scores = [round(1.0 / (1.0 + d), 4) for d in distances] if distances else []
        sources = [m.get("source", "unknown") for m in metadatas] if metadatas else []

        duration_ms = int((time.time() - start) * 1000)
        result.update({
            "documents": documents,
            "scores": scores,
            "sources": sources,
            "distances_raw": [round(d, 4) for d in distances] if distances else [],
            "duration_ms": duration_ms,
        })
        debug_log("RAG", {
            "query": query,
            "num_results": len(documents),
            "scores": scores,
            "sources": sources,
            "distances_raw": result["distances_raw"],
            "duration_ms": duration_ms,
            "doc_previews": [d[:100] + "..." for d in documents] if documents else [],
        })
    except Exception as e:
        debug_log("RAG", {"error": str(e), "query": query})
    return result


def build_draft_prompt(
    docs: List[str],
    eng_query: str,
    target_lang: str,
    weather: str = "",
    symptoms: str = "",
) -> str:
    context = "\n\n".join(docs)
    return f"""You are a strict agricultural advisor in India.
Context from official guidelines:
{context}

User Query (English): {eng_query}
Image Symptoms: {symptoms}
Weather Context: {weather}

1. Analyze the context and the user query.
2. Answer the query based ONLY on the context provided above.
3. If the context does not contain the answer, or if the user asks for a banned chemical, you MUST output EXACTLY: "I do not have enough verified information to answer this safely. Please consult your local Krishi Vigyan Kendra (KVK) official or agricultural officer."
4. DO NOT guess or hallucinate.
5. Translate your final response into {target_lang}. Use simple, conversational language suitable for a farmer. Output your final response in {target_lang}.
"""


def get_vision_response(
    image_bytes: bytes, prompt: str, model: str = OLLAMA_VISION_MODEL
) -> Dict[str, Any]:
    """Helper to query Ollama Vision models. Returns dict with symptoms + metadata."""
    start = time.time()
    result: Dict[str, Any] = {
        "symptoms": "",
        "model": model,
        "image_size_bytes": len(image_bytes),
        "duration_ms": 0,
        "error": None,
    }

    debug_log("VISION_START", {
        "model": model,
        "image_size_bytes": len(image_bytes),
        "image_size_kb": round(len(image_bytes) / 1024, 1),
        "prompt": prompt,
    })

    try:
        b64_image = base64.b64encode(image_bytes).decode("utf-8")
        response = ollama_client.chat(
            model=model,
            messages=[{"role": "user", "content": prompt, "images": [b64_image]}],
        )
        raw_content = response.get("message", {}).get("content", "")
        symptoms = clean_think_tags(raw_content)
        duration_ms = int((time.time() - start) * 1000)

        result.update({
            "symptoms": symptoms,
            "raw_response": raw_content[:500],
            "duration_ms": duration_ms,
        })
        debug_log("VISION_DONE", {
            "model": model,
            "symptoms_extracted": symptoms,
            "raw_response_length": len(raw_content),
            "duration_ms": duration_ms,
        })
    except Exception as e:
        duration_ms = int((time.time() - start) * 1000)
        error_msg = f"[Error: Unable to analyze image using '{model}': {e}]"
        result.update({
            "symptoms": error_msg,
            "error": str(e),
            "duration_ms": duration_ms,
        })
        debug_log("VISION_ERROR", {
            "model": model,
            "error": str(e),
            "duration_ms": duration_ms,
        })
    return result
